name: Macaroni
options:
  bundleIdPrefix: com.macaroni
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: "43QM98RMK6"
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGN_STYLE: Automatic

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  SimplyCoreAudio:
    url: https://github.com/rnine/SimplyCoreAudio
    from: "4.0.0"
  Solar:
    url: https://github.com/ceeK/Solar
    from: "3.0.0"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: "1.0.0"

targets:
  Macaroni:
    type: application
    platform: macOS
    sources:
      - path: Macaroni
        excludes:
          - "**/*.xcassets"
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macaroni.app
        INFOPLIST_FILE: Macaroni/App/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "43QM98RMK6"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Macaroni/Macaroni.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: Macaroni/Macaroni-Bridging-Header.h
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "/System/Library/PrivateFrameworks"
        OTHER_LDFLAGS:
          - "-weak_framework"
          - "IOMobileFramebuffer"
          - "-weak_framework"
          - "CoreDisplay"
          - "-weak_framework"
          - "DisplayServices"
    dependencies:
      - package: KeyboardShortcuts
      - package: SimplyCoreAudio
      - package: Solar
      - package: LaunchAtLogin
      - target: MacaroniAudioProxy
        embed: true
        codeSign: true
      - target: MacaroniCameraExtension
        embed: true
        codeSign: true
      - target: MacaroniFanHelper
        embed: false
    postBuildScripts:
      - script: |
          # Copy fan helper and plist to Resources folder
          HELPER_SRC="${BUILT_PRODUCTS_DIR}/com.macaroni.fanhelper"
          PLIST_SRC="${SRCROOT}/MacaroniFanHelper/com.macaroni.fanhelper.plist"
          RESOURCES_DIR="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources"

          if [ -f "$HELPER_SRC" ]; then
            cp "$HELPER_SRC" "$RESOURCES_DIR/"
            echo "Copied fan helper to Resources"
          fi

          if [ -f "$PLIST_SRC" ]; then
            cp "$PLIST_SRC" "$RESOURCES_DIR/"
            echo "Copied fan helper plist to Resources"
          fi
        name: Copy Fan Helper to Resources
    entitlements:
      path: Macaroni/Macaroni.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.device.camera: true
        com.apple.developer.system-extension.install: true
        com.apple.security.application-groups:
          - "43QM98RMK6.com.macaroni.app"

  MacaroniCameraExtension:
    type: system-extension
    platform: macOS
    sources:
      - path: MacaroniCameraExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macaroni.app.camera-extension
        PRODUCT_NAME: com.macaroni.app.camera-extension
        INFOPLIST_FILE: MacaroniCameraExtension/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "43QM98RMK6"
        CODE_SIGN_ENTITLEMENTS: MacaroniCameraExtension/MacaroniCameraExtension.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        SKIP_INSTALL: YES

  MacaroniAudioExtension:
    type: driver-extension
    platform: macOS
    sources:
      - path: MacaroniAudioExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macaroni.app.audio-extension
        PRODUCT_NAME: MacaroniAudioExtension
        INFOPLIST_FILE: MacaroniAudioExtension/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "43QM98RMK6"
        CODE_SIGN_ENTITLEMENTS: MacaroniAudioExtension/MacaroniAudioExtension.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        SKIP_INSTALL: YES
        ARCHS: "$(ARCHS_STANDARD)"
        SDKROOT: driverkit
        DRIVERKIT_DEPLOYMENT_TARGET: "23.0"
        CLANG_CXX_LANGUAGE_STANDARD: "c++20"
        OTHER_LDFLAGS:
          - "-framework"
          - "AudioDriverKit"
          - "-framework"
          - "DriverKit"

  MacaroniFanHelper:
    type: tool
    platform: macOS
    sources:
      - path: MacaroniFanHelper
        excludes:
          - "*.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macaroni.fanhelper
        PRODUCT_NAME: com.macaroni.fanhelper
        INFOPLIST_FILE: MacaroniFanHelper/Info.plist
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: NO
        INSTALL_PATH: /Library/PrivilegedHelperTools

  MacaroniAudioProxy:
    type: bundle
    platform: macOS
    sources:
      - path: MacaroniAudioProxy/Source
      - path: MacaroniAudioProxy/PublicUtility
      - path: MacaroniAudioProxy/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.briankendall.ProxyAudioDevice
        PRODUCT_NAME: MacaroniAudioProxy
        INFOPLIST_FILE: MacaroniAudioProxy/Info.plist
        WRAPPER_EXTENSION: driver
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        CLANG_CXX_LANGUAGE_STANDARD: "c++17"
        GCC_ENABLE_CPP_EXCEPTIONS: YES
        GCC_ENABLE_CPP_RTTI: YES
        HEADER_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/MacaroniAudioProxy/Source"
          - "$(SRCROOT)/MacaroniAudioProxy/PublicUtility"
        OTHER_LDFLAGS:
          - "-framework"
          - "CoreFoundation"
          - "-framework"
          - "CoreAudio"
          - "-framework"
          - "IOKit"
        SKIP_INSTALL: YES

schemes:
  Macaroni:
    build:
      targets:
        Macaroni: all
        MacaroniCameraExtension: all
        MacaroniFanHelper: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
